framework:
    serializer:
        enabled: true
        enable_attributes: true
        name_converter: ~
        circular_reference_handler: ~
        max_depth_handler: ~
        default_context:
            enable_max_depth: true
